### ISSUE TITLE
Whatsapp colors

### ISSUE THREAD

**Issue by edilsonmatola** [edilsonmatola/whatsapp_ui_flutter#3]
### Put **color scheme** same as whatsapp app. Maybe organizing it in a file called `colors.dart` will make it easier.

**Comment by UrvashiKoladiya** [comment]
@edilsonmatola Can i work on this?

**Comment by urvi-k** [comment]
@edilsonmatola Can i work on this?

**Comment by edilsonmatola** [comment]
Hey @urvi-k, glad to hear you want to contribute.

Feel free to take it after making sure you're good with the guidelines in [CONTRIBUTING.md](https://github.com/edilsonmatola/whatsapp_ui_flutter/blob/main/CONTRIBUTING.md). If you have any questions, let me know.

**Comment by urvi-k** [comment]
@edilsonmatola Please review the changes: https://github.com/edilsonmatola/whatsapp_ui_flutter/pull/5

Note: I've created the pull request to develop branch as i couldn't found big-features branch in your repo, please let me know if you have any changes and questions regarding PR.
Thanks.
